import React from 'react';
export default function Services() {
  return <main id="main"><section className="page-hero"><div className="shell"><p className="section-kicker">01 / TJÄNSTER</p><h1>El för fler<br />sammanhang.</h1><p>Elteam hjälper privatpersoner, företag och fastighetsägare med elarbete i Malmö och övriga Skåne.</p></div></section><section className="service-section section-pad"><div className="shell"><div className="section-heading"><p className="section-kicker">VÅRA OMRÅDEN</p><h2>Det här kan<br /><span>vi hjälpa till med.</span></h2><p>Välj ett område och läs mer.</p></div><div className="service-ledger">
        <a className="service-row" href="/elinstallationer/"><span className="service-number">01</span><span className="service-name">Elinstallationer<small>Nyinstallation · renovering · service</small></span><span className="service-row-arrow" aria-hidden="true">↗</span></a>
        <a className="service-row" href="/laddbox/"><span className="service-number">02</span><span className="service-name">Laddboxar<small>Installation för hem och arbete</small></span><span className="service-row-arrow" aria-hidden="true">↗</span></a>
        <a className="service-row" href="/storkok/"><span className="service-number">03</span><span className="service-name">Storkök<small>Installation · renovering</small></span><span className="service-row-arrow" aria-hidden="true">↗</span></a>
        <a className="service-row" href="/solceller/"><span className="service-number">04</span><span className="service-name">Solceller<small>Installation</small></span><span className="service-row-arrow" aria-hidden="true">↗</span></a>
        </div></div></section><section className="page-main"><div className="shell section-pad page-intro"><div><p className="section-kicker">ERFARENHET SEDAN 1988</p><h2>Det lilla jobbet.<br />Det stora projektet.</h2></div><div className="body"><p>Elteam utför bland annat installationer vid tillbyggnader, renoveringar, kök och kontor. Tidigare arbeten omfattar även bostäder, skolmiljöer och storkök.</p><p>Berätta vad du behöver hjälp med, så börjar vi där.</p><a className="text-link" href="/kontakt/">Skicka en förfrågan <span aria-hidden="true">↗</span></a></div></div></section><section className="page-cta"><div className="shell"><div><p className="section-kicker" style={{'color': '#fff'}}>NÄSTA STEG</p><h2>Berätta vad du behöver hjälp med.</h2></div><a className="button" href="/kontakt/">Kontakta Elteam <span aria-hidden="true">↗</span></a></div></section></main>;
}
